package com.cdac.respository;

import org.springframework.data.repository.CrudRepository;

import com.cdac.entity.Album;

//Repository is ANOTHER NAME FOR "DAO"
public interface AlbumRepository extends CrudRepository<Album,Integer> {

	//Now dao is ready ---> Remaining code is written or generated by Spring
		// SELECT statement aplyala lihava lagnar 
}
