package com.cdac.respository;

import java.util.List;

import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.CrudRepository;

import com.cdac.entity.Album;
import com.cdac.entity.Song;

public interface SongRepository extends CrudRepository<Song,Integer> {
	
	//Album,Integer
	//album ---> Entity 
	//Integer ---> Type of primary key
	
	//Now dao is ready ---> Remaining code is written or generated by Spring
	// SELECT statement aplyala lihava lagnar
	
	// This is for when we follow naming convention
	public List<Song> findSongByArtist (String artist);
	
	
	// This is for when we doesn't follow naming convention
	@Query("select s from Song s where s.artist = ?1")
	public List<Song> fetchSongsSungBy(String artist);
	//?1 --- > no of parameteres passed in the brackets and we pass Ellie goulding
}
